#!/usr/bin/env bash
# Install nginx web server
apt-get -y update
apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/defult
ufw allow 'Nginx HTTP'
echo Holberton School > /var/www/html/index.nginx-debian.html
service nginx start
