#!/usr/bin/env bash
# Script that modifies nginx config
# for a redirection
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo Holberton School > /var/www/html/index.nginx-debian.html
sed -i "/^\sserver_name.*/a\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default;
service nginx start
