#!/usr/bin/env bash
# script that displays cd in ls format
# The content of the cd
# In a list format
# Where only the part of the name after the first dash is displayed
for file in *
do
	if [ -f "$file" ]
	then
		echo "$file" | cut -d "-" -f 2-
	fi
done
