#!/usr/bin/env bash
# configures the container to fit the above requirements
# nginx must be running as nginx use
# nginx must be listening on all active IPs on port 8080

# change group nginx
chown nginx:nginx /etc/nginx/nginx.conf

# change permision to owner
chmod 700 /etc/nginx/nginx.conf

# changes port from 80 to 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# restart nginx
sudo -u nginx service nginx restart
